spring:
  application:
    name: desk-nova

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    baseline-on-migrate: true

  #email properties
  mail:
    #host: smtp.office365.com
    host: sandbox.smtp.mailtrap.io
    port: 2525
    #587 2525
    username: f8149413ba1420
    password: 79f6e744f15c04
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: "lK9zQw7h2VfYpR3uXn8aJt5mC4dHb0oGqTwZcN5vXyB8eFsUjLkM7r1nEy6vPa="
  expiration: 86400000

server:
  port: ${PORT:8080}