spring:
  application:
    name: desk-nova

  datasource:
    url: jdbc:mysql://localhost:3306/desk_nova?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: B0ch0g
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    baseline-on-migrate: true

  #email properties
  mail:
    #host: smtp.office365.com
    host: smtp.gmail.com
    port: 587
    #587 2525
    username: desk.nova.info@gmail.com
    password: xqfz hjfz zhzt yrmd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: "BhNkCusVh80QcdKicwzYgXR6vtDfrRi27KdjF/4V/BSITtcVGz/bXioIBNQxW782riM1tgCWDjpnlqQjD/lDQg=="
  expiration: 86400000

